image: docker:19.03

services:
  - docker:19.03-dind

variables:
  CONTAINER_IMAGE: $CI_REGISTRY_IMAGE
  DOCKER_DRIVER: overlay2
  DOCKER_BUILDKIT: 1
  POSTGRES_HOST_AUTH_METHOD: trust


stages:
  - build
  - deploy

before_script:
  - docker version
  - echo -n $CI_JOB_TOKEN | docker login -u gitlab-ci-token --password-stdin $CI_REGISTRY

build:
  stage: build
  script:
    - docker pull $CONTAINER_IMAGE:latest || true
    - docker build
        --cache-from $CONTAINER_IMAGE:latest
        --tag $CONTAINER_IMAGE:$CI_COMMIT_SHA
        --build-arg BUILDKIT_INLINE_CACHE=1
        "."
  after_script:
    - docker push $CONTAINER_IMAGE:$CI_COMMIT_SHA

release:
  stage: deploy
  script:
    - docker pull $CONTAINER_IMAGE:$CI_COMMIT_SHA
    - docker tag $CONTAINER_IMAGE:$CI_COMMIT_SHA $CONTAINER_IMAGE:latest
    - docker push $CONTAINER_IMAGE:latest
  only:
    - main
