from datetime import date
from typing import Any  # noqa
from typing import List, Optional
from uuid import UUID

from pydantic import BaseModel, Field


class Power(BaseModel):
    id: "Optional[UUID]" = Field(None, alias="id")
    developer: "Optional[str]" = Field(None, alias="developer")
    notice: "Optional[str]" = Field(None, alias="notice")
    picture_source: "Optional[str]" = Field(None, alias="picture_source")
    sponsor_id: "Optional[UUID]" = Field(None, alias="sponsor_id")
    full_name: "Optional[str]" = Field(None, alias="full_name")
    short_name: "Optional[str]" = Field(None, alias="short_name")
    capacity_id: "Optional[UUID]" = Field(None, alias="capacity_id")
    size: "Optional[float]" = Field(None, alias="size")
    description: "Optional[str]" = Field(None, alias="description")
    sector_id: "Optional[str]" = Field(None, alias="sector_id")
    energy_resource_id: "Optional[UUID]" = Field(None, alias="energy_resource_id")
    technology_id: "Optional[UUID]" = Field(None, alias="technology_id")
    hydropower_type_id: "Optional[UUID]" = Field(None, alias="hydropower_type_id")
    other_technologies: "Optional[str]" = Field(None, alias="other_technologies")
    waterbody_names: "Optional[str]" = Field(None, alias="waterbody_names")
    scheme: "Optional[str]" = Field(None, alias="scheme")
    design_components: "Optional[str]" = Field(None, alias="design_components")
    unit_id: "Optional[str]" = Field(None, alias="unit_id")
    average_length: "Optional[float]" = Field(None, alias="average_length")
    average_width: "Optional[float]" = Field(None, alias="average_width")
    off_taker_id: "Optional[UUID]" = Field(None, alias="off_taker_id")
    statutory_permits: "Optional[str]" = Field(None, alias="statutory_permits")
    ppa_status_id: "Optional[UUID]" = Field(None, alias="ppa_status_id")
    ppa_status_grid_id: "Optional[UUID]" = Field(None, alias="ppa_status_grid_id")
    data_shareable_public: "Optional[bool]" = Field(None, alias="data_shareable_public")
    data_shareable_local: "Optional[bool]" = Field(None, alias="data_shareable_local")


class PowerCreate(BaseModel):
    id: "Optional[UUID]" = Field(None, alias="id")
    developer: "Optional[str]" = Field(None, alias="developer")
    notice: "Optional[str]" = Field(None, alias="notice")
    picture_source: "Optional[str]" = Field(None, alias="picture_source")
    sponsor_id: "Optional[UUID]" = Field(None, alias="sponsor_id")
    full_name: "Optional[str]" = Field(None, alias="full_name")
    short_name: "Optional[str]" = Field(None, alias="short_name")
    capacity_id: "Optional[UUID]" = Field(None, alias="capacity_id")
    size: "Optional[float]" = Field(None, alias="size")
    description: "Optional[str]" = Field(None, alias="description")
    sector_id: "Optional[str]" = Field(None, alias="sector_id")
    energy_resource_id: "Optional[UUID]" = Field(None, alias="energy_resource_id")
    technology_id: "Optional[UUID]" = Field(None, alias="technology_id")
    hydropower_type_id: "Optional[UUID]" = Field(None, alias="hydropower_type_id")
    other_technologies: "Optional[str]" = Field(None, alias="other_technologies")
    waterbody_names: "Optional[str]" = Field(None, alias="waterbody_names")
    scheme: "Optional[str]" = Field(None, alias="scheme")
    design_components: "Optional[str]" = Field(None, alias="design_components")
    unit_id: "Optional[str]" = Field(None, alias="unit_id")
    average_length: "Optional[float]" = Field(None, alias="average_length")
    average_width: "Optional[float]" = Field(None, alias="average_width")
    off_taker_id: "Optional[UUID]" = Field(None, alias="off_taker_id")
    statutory_permits: "Optional[str]" = Field(None, alias="statutory_permits")
    ppa_status_id: "Optional[UUID]" = Field(None, alias="ppa_status_id")
    ppa_status_grid_id: "Optional[UUID]" = Field(None, alias="ppa_status_grid_id")
    data_shareable_public: "Optional[bool]" = Field(None, alias="data_shareable_public")
    data_shareable_local: "Optional[bool]" = Field(None, alias="data_shareable_local")


class PowerImpact(BaseModel):
    id: "Optional[UUID]" = Field(None, alias="id")
    description_environment: "Optional[str]" = Field(None, alias="description_environment")
    description_social: "Optional[str]" = Field(None, alias="description_social")
    description_environment_impact: "Optional[str]" = Field(None, alias="description_environment_impact")
    description_social_impact: "Optional[str]" = Field(None, alias="description_social_impact")
    treatment_plans: "Optional[str]" = Field(None, alias="treatment_plans")
    occupational_hazards: "Optional[str]" = Field(None, alias="occupational_hazards")
    local_regulations: "Optional[str]" = Field(None, alias="local_regulations")
    sponsor_contribution: "Optional[str]" = Field(None, alias="sponsor_contribution")
    key_partners: "Optional[str]" = Field(None, alias="key_partners")
    environmental_concerns: "Optional[str]" = Field(None, alias="environmental_concerns")
    esmp: "Optional[str]" = Field(None, alias="esmp")


class PowerImpactCreate(BaseModel):
    id: "Optional[UUID]" = Field(None, alias="id")
    description_environment: "Optional[str]" = Field(None, alias="description_environment")
    description_social: "Optional[str]" = Field(None, alias="description_social")
    description_environment_impact: "Optional[str]" = Field(None, alias="description_environment_impact")
    description_social_impact: "Optional[str]" = Field(None, alias="description_social_impact")
    treatment_plans: "Optional[str]" = Field(None, alias="treatment_plans")
    occupational_hazards: "Optional[str]" = Field(None, alias="occupational_hazards")
    local_regulations: "Optional[str]" = Field(None, alias="local_regulations")
    sponsor_contribution: "Optional[str]" = Field(None, alias="sponsor_contribution")
    key_partners: "Optional[str]" = Field(None, alias="key_partners")
    environmental_concerns: "Optional[str]" = Field(None, alias="environmental_concerns")
    esmp: "Optional[str]" = Field(None, alias="esmp")


class PowerImpactListResponse(BaseModel):
    success: "bool" = Field(..., alias="success")
    data: "Optional[List[PowerImpact]]" = Field(None, alias="data")


class PowerImpactResponse(BaseModel):
    success: "bool" = Field(..., alias="success")
    data: "PowerImpact" = Field(..., alias="data")


class PowerImpactUpdate(BaseModel):
    id: "Optional[UUID]" = Field(None, alias="id")
    description_environment: "Optional[str]" = Field(None, alias="description_environment")
    description_social: "Optional[str]" = Field(None, alias="description_social")
    description_environment_impact: "Optional[str]" = Field(None, alias="description_environment_impact")
    description_social_impact: "Optional[str]" = Field(None, alias="description_social_impact")
    treatment_plans: "Optional[str]" = Field(None, alias="treatment_plans")
    occupational_hazards: "Optional[str]" = Field(None, alias="occupational_hazards")
    local_regulations: "Optional[str]" = Field(None, alias="local_regulations")
    sponsor_contribution: "Optional[str]" = Field(None, alias="sponsor_contribution")
    key_partners: "Optional[str]" = Field(None, alias="key_partners")
    environmental_concerns: "Optional[str]" = Field(None, alias="environmental_concerns")
    esmp: "Optional[str]" = Field(None, alias="esmp")


class PowerListResponse(BaseModel):
    success: "bool" = Field(..., alias="success")
    data: "Optional[List[Power]]" = Field(None, alias="data")


class PowerResponse(BaseModel):
    success: "bool" = Field(..., alias="success")
    data: "Power" = Field(..., alias="data")


class PowerSchedule(BaseModel):
    id: "Optional[UUID]" = Field(None, alias="id")
    construction_schedule: "Optional[str]" = Field(None, alias="construction_schedule")
    startup_schedule: "Optional[str]" = Field(None, alias="startup_schedule")
    operations_schedule: "Optional[str]" = Field(None, alias="operations_schedule")
    expenditures: "Optional[str]" = Field(None, alias="expenditures")
    funding_schedule: "Optional[str]" = Field(None, alias="funding_schedule")
    regulatory_compliance: "Optional[str]" = Field(None, alias="regulatory_compliance")


class PowerScheduleCreate(BaseModel):
    id: "Optional[UUID]" = Field(None, alias="id")
    construction_schedule: "Optional[str]" = Field(None, alias="construction_schedule")
    startup_schedule: "Optional[str]" = Field(None, alias="startup_schedule")
    operations_schedule: "Optional[str]" = Field(None, alias="operations_schedule")
    expenditures: "Optional[str]" = Field(None, alias="expenditures")
    funding_schedule: "Optional[str]" = Field(None, alias="funding_schedule")
    regulatory_compliance: "Optional[str]" = Field(None, alias="regulatory_compliance")


class PowerScheduleListResponse(BaseModel):
    success: "bool" = Field(..., alias="success")
    data: "Optional[List[PowerSchedule]]" = Field(None, alias="data")


class PowerScheduleResponse(BaseModel):
    success: "bool" = Field(..., alias="success")
    data: "PowerSchedule" = Field(..., alias="data")


class PowerScheduleUpdate(BaseModel):
    id: "Optional[UUID]" = Field(None, alias="id")
    construction_schedule: "Optional[str]" = Field(None, alias="construction_schedule")
    startup_schedule: "Optional[str]" = Field(None, alias="startup_schedule")
    operations_schedule: "Optional[str]" = Field(None, alias="operations_schedule")
    expenditures: "Optional[str]" = Field(None, alias="expenditures")
    funding_schedule: "Optional[str]" = Field(None, alias="funding_schedule")
    regulatory_compliance: "Optional[str]" = Field(None, alias="regulatory_compliance")


class PowerUpdate(BaseModel):
    id: "Optional[UUID]" = Field(None, alias="id")
    developer: "Optional[str]" = Field(None, alias="developer")
    notice: "Optional[str]" = Field(None, alias="notice")
    picture_source: "Optional[str]" = Field(None, alias="picture_source")
    sponsor_id: "Optional[UUID]" = Field(None, alias="sponsor_id")
    full_name: "Optional[str]" = Field(None, alias="full_name")
    short_name: "Optional[str]" = Field(None, alias="short_name")
    capacity_id: "Optional[UUID]" = Field(None, alias="capacity_id")
    size: "Optional[float]" = Field(None, alias="size")
    description: "Optional[str]" = Field(None, alias="description")
    sector_id: "Optional[str]" = Field(None, alias="sector_id")
    energy_resource_id: "Optional[UUID]" = Field(None, alias="energy_resource_id")
    technology_id: "Optional[UUID]" = Field(None, alias="technology_id")
    hydropower_type_id: "Optional[UUID]" = Field(None, alias="hydropower_type_id")
    other_technologies: "Optional[str]" = Field(None, alias="other_technologies")
    waterbody_names: "Optional[str]" = Field(None, alias="waterbody_names")
    scheme: "Optional[str]" = Field(None, alias="scheme")
    design_components: "Optional[str]" = Field(None, alias="design_components")
    unit_id: "Optional[str]" = Field(None, alias="unit_id")
    average_length: "Optional[float]" = Field(None, alias="average_length")
    average_width: "Optional[float]" = Field(None, alias="average_width")
    off_taker_id: "Optional[UUID]" = Field(None, alias="off_taker_id")
    statutory_permits: "Optional[str]" = Field(None, alias="statutory_permits")
    ppa_status_id: "Optional[UUID]" = Field(None, alias="ppa_status_id")
    ppa_status_grid_id: "Optional[UUID]" = Field(None, alias="ppa_status_grid_id")
    data_shareable_public: "Optional[bool]" = Field(None, alias="data_shareable_public")
    data_shareable_local: "Optional[bool]" = Field(None, alias="data_shareable_local")


class Project(BaseModel):
    id: "Optional[UUID]" = Field(None, alias="id")
    name: "Optional[str]" = Field(None, alias="name")
    description: "Optional[str]" = Field(None, alias="description")
    size: "Optional[float]" = Field(None, alias="size")
    investment: "Optional[float]" = Field(None, alias="investment")
    country_id: "Optional[str]" = Field(None, alias="country_id")
    sector_industry_id: "Optional[str]" = Field(None, alias="sector_industry_id")
    sector_group_id: "Optional[str]" = Field(None, alias="sector_group_id")
    sector_division_id: "Optional[str]" = Field(None, alias="sector_division_id")
    sector_id: "Optional[str]" = Field(None, alias="sector_id")
    technology: "Optional[str]" = Field(None, alias="technology")
    status: "Optional[str]" = Field(None, alias="status")
    commencement_date: "Optional[date]" = Field(None, alias="commencement_date")
    proposed_completion_date: "Optional[date]" = Field(None, alias="proposed_completion_date")
    current_stage: "Optional[str]" = Field(None, alias="current_stage")
    next_stages: "Optional[str]" = Field(None, alias="next_stages")
    estimated_cost: "Optional[float]" = Field(None, alias="estimated_cost")
    contact_information: "Optional[str]" = Field(None, alias="contact_information")
    contact_address: "Optional[str]" = Field(None, alias="contact_address")
    postal_address: "Optional[str]" = Field(None, alias="postal_address")
    telephone: "Optional[str]" = Field(None, alias="telephone")
    email: "Optional[str]" = Field(None, alias="email")
    website: "Optional[str]" = Field(None, alias="website")
    completed_activities: "Optional[str]" = Field(None, alias="completed_activities")
    current_activities: "Optional[str]" = Field(None, alias="current_activities")
    next_activities: "Optional[str]" = Field(None, alias="next_activities")
    outstanding_activities: "Optional[str]" = Field(None, alias="outstanding_activities")
    status_id: "Optional[str]" = Field(None, alias="status_id")
    sponsor_type_id: "Optional[UUID]" = Field(None, alias="sponsor_type_id")
    reference_code: "Optional[str]" = Field(None, alias="reference_code")
    manager: "Optional[str]" = Field(None, alias="manager")
    development_type_id: "Optional[UUID]" = Field(None, alias="development_type_id")
    development_model_id: "Optional[UUID]" = Field(None, alias="development_model_id")
    percentage_public: "Optional[float]" = Field(None, alias="percentage_public")
    percentage_private: "Optional[float]" = Field(None, alias="percentage_private")
    location: "Optional[str]" = Field(None, alias="location")
    nearest_town: "Optional[str]" = Field(None, alias="nearest_town")
    distance: "Optional[float]" = Field(None, alias="distance")
    nearest_capital_country_id: "Optional[str]" = Field(None, alias="nearest_capital_country_id")
    nearest_capital: "Optional[str]" = Field(None, alias="nearest_capital")
    distance_capital: "Optional[float]" = Field(None, alias="distance_capital")
    environmental_impact: "Optional[str]" = Field(None, alias="environmental_impact")
    social_impact: "Optional[str]" = Field(None, alias="social_impact")
    total_investment: "Optional[float]" = Field(None, alias="total_investment")
    equity_investment: "Optional[float]" = Field(None, alias="equity_investment")
    debt_amount: "Optional[float]" = Field(None, alias="debt_amount")
    grant_amount: "Optional[float]" = Field(None, alias="grant_amount")
    outstanding_investment: "Optional[float]" = Field(None, alias="outstanding_investment")
    related_projects: "Optional[str]" = Field(None, alias="related_projects")
    strategy: "Optional[str]" = Field(None, alias="strategy")
    alliances: "Optional[str]" = Field(None, alias="alliances")


class ProjectCreate(BaseModel):
    id: "Optional[UUID]" = Field(None, alias="id")
    name: "Optional[str]" = Field(None, alias="name")
    description: "Optional[str]" = Field(None, alias="description")
    size: "Optional[float]" = Field(None, alias="size")
    investment: "Optional[float]" = Field(None, alias="investment")
    country_id: "Optional[str]" = Field(None, alias="country_id")
    sector_industry_id: "Optional[str]" = Field(None, alias="sector_industry_id")
    sector_group_id: "Optional[str]" = Field(None, alias="sector_group_id")
    sector_division_id: "Optional[str]" = Field(None, alias="sector_division_id")
    sector_id: "Optional[str]" = Field(None, alias="sector_id")
    technology: "Optional[str]" = Field(None, alias="technology")
    status: "Optional[str]" = Field(None, alias="status")
    commencement_date: "Optional[date]" = Field(None, alias="commencement_date")
    proposed_completion_date: "Optional[date]" = Field(None, alias="proposed_completion_date")
    current_stage: "Optional[str]" = Field(None, alias="current_stage")
    next_stages: "Optional[str]" = Field(None, alias="next_stages")
    estimated_cost: "Optional[float]" = Field(None, alias="estimated_cost")
    contact_information: "Optional[str]" = Field(None, alias="contact_information")
    contact_address: "Optional[str]" = Field(None, alias="contact_address")
    postal_address: "Optional[str]" = Field(None, alias="postal_address")
    telephone: "Optional[str]" = Field(None, alias="telephone")
    email: "Optional[str]" = Field(None, alias="email")
    website: "Optional[str]" = Field(None, alias="website")
    completed_activities: "Optional[str]" = Field(None, alias="completed_activities")
    current_activities: "Optional[str]" = Field(None, alias="current_activities")
    next_activities: "Optional[str]" = Field(None, alias="next_activities")
    outstanding_activities: "Optional[str]" = Field(None, alias="outstanding_activities")
    status_id: "Optional[str]" = Field(None, alias="status_id")
    sponsor_type_id: "Optional[UUID]" = Field(None, alias="sponsor_type_id")
    reference_code: "Optional[str]" = Field(None, alias="reference_code")
    manager: "Optional[str]" = Field(None, alias="manager")
    development_type_id: "Optional[UUID]" = Field(None, alias="development_type_id")
    development_model_id: "Optional[UUID]" = Field(None, alias="development_model_id")
    percentage_public: "Optional[float]" = Field(None, alias="percentage_public")
    percentage_private: "Optional[float]" = Field(None, alias="percentage_private")
    location: "Optional[str]" = Field(None, alias="location")
    nearest_town: "Optional[str]" = Field(None, alias="nearest_town")
    distance: "Optional[float]" = Field(None, alias="distance")
    nearest_capital_country_id: "Optional[str]" = Field(None, alias="nearest_capital_country_id")
    nearest_capital: "Optional[str]" = Field(None, alias="nearest_capital")
    distance_capital: "Optional[float]" = Field(None, alias="distance_capital")
    environmental_impact: "Optional[str]" = Field(None, alias="environmental_impact")
    social_impact: "Optional[str]" = Field(None, alias="social_impact")
    total_investment: "Optional[float]" = Field(None, alias="total_investment")
    equity_investment: "Optional[float]" = Field(None, alias="equity_investment")
    debt_amount: "Optional[float]" = Field(None, alias="debt_amount")
    grant_amount: "Optional[float]" = Field(None, alias="grant_amount")
    outstanding_investment: "Optional[float]" = Field(None, alias="outstanding_investment")
    related_projects: "Optional[str]" = Field(None, alias="related_projects")
    strategy: "Optional[str]" = Field(None, alias="strategy")
    alliances: "Optional[str]" = Field(None, alias="alliances")


class ProjectData(BaseModel):
    id: "Optional[UUID]" = Field(None, alias="id")
    height: "Optional[str]" = Field(None, alias="height")
    size_class: "Optional[str]" = Field(None, alias="size_class")
    hazard_potential: "Optional[str]" = Field(None, alias="hazard_potential")
    type_of_dam: "Optional[str]" = Field(None, alias="type_of_dam")
    dam_length: "Optional[float]" = Field(None, alias="dam_length")
    crest_width: "Optional[float]" = Field(None, alias="crest_width")
    catchment_area: "Optional[float]" = Field(None, alias="catchment_area")
    design_flow: "Optional[float]" = Field(None, alias="design_flow")
    maximum_flood: "Optional[float]" = Field(None, alias="maximum_flood")
    q100: "Optional[float]" = Field(None, alias="q100")
    q200: "Optional[float]" = Field(None, alias="q200")
    canal_length: "Optional[float]" = Field(None, alias="canal_length")
    canal_width: "Optional[float]" = Field(None, alias="canal_width")
    canal_velocity: "Optional[float]" = Field(None, alias="canal_velocity")
    spillway_type: "Optional[str]" = Field(None, alias="spillway_type")
    spillway_length: "Optional[float]" = Field(None, alias="spillway_length")
    spillway_free_board: "Optional[float]" = Field(None, alias="spillway_free_board")
    spillway_discharge_capacity: "Optional[float]" = Field(None, alias="spillway_discharge_capacity")
    penstocks_type: "Optional[str]" = Field(None, alias="penstocks_type")
    penstocks_diameter: "Optional[float]" = Field(None, alias="penstocks_diameter")
    penstocks_velocity: "Optional[float]" = Field(None, alias="penstocks_velocity")
    penstocks_thickness: "Optional[float]" = Field(None, alias="penstocks_thickness")
    penstocks_number: "Optional[float]" = Field(None, alias="penstocks_number")
    installation_method: "Optional[str]" = Field(None, alias="installation_method")
    upstream_control: "Optional[str]" = Field(None, alias="upstream_control")
    inlet_control: "Optional[str]" = Field(None, alias="inlet_control")
    outlet_control: "Optional[str]" = Field(None, alias="outlet_control")
    overhead_crane: "Optional[float]" = Field(None, alias="overhead_crane")
    turbine_type: "Optional[str]" = Field(None, alias="turbine_type")
    turbine_capacity_id: "Optional[UUID]" = Field(None, alias="turbine_capacity_id")
    turbine_numbers: "Optional[int]" = Field(None, alias="turbine_numbers")
    turbine_capacity: "Optional[float]" = Field(None, alias="turbine_capacity")
    turbine_efficiency: "Optional[float]" = Field(None, alias="turbine_efficiency")
    turbine_capacity_flow: "Optional[float]" = Field(None, alias="turbine_capacity_flow")
    alternator_power_output: "Optional[float]" = Field(None, alias="alternator_power_output")
    alternator_number: "Optional[int]" = Field(None, alias="alternator_number")
    alternator_voltage: "Optional[float]" = Field(None, alias="alternator_voltage")
    substation_power_output: "Optional[float]" = Field(None, alias="substation_power_output")
    substation_voltage: "Optional[float]" = Field(None, alias="substation_voltage")


class ProjectDataCreate(BaseModel):
    id: "Optional[UUID]" = Field(None, alias="id")
    height: "Optional[str]" = Field(None, alias="height")
    size_class: "Optional[str]" = Field(None, alias="size_class")
    hazard_potential: "Optional[str]" = Field(None, alias="hazard_potential")
    type_of_dam: "Optional[str]" = Field(None, alias="type_of_dam")
    dam_length: "Optional[float]" = Field(None, alias="dam_length")
    crest_width: "Optional[float]" = Field(None, alias="crest_width")
    catchment_area: "Optional[float]" = Field(None, alias="catchment_area")
    design_flow: "Optional[float]" = Field(None, alias="design_flow")
    maximum_flood: "Optional[float]" = Field(None, alias="maximum_flood")
    q100: "Optional[float]" = Field(None, alias="q100")
    q200: "Optional[float]" = Field(None, alias="q200")
    canal_length: "Optional[float]" = Field(None, alias="canal_length")
    canal_width: "Optional[float]" = Field(None, alias="canal_width")
    canal_velocity: "Optional[float]" = Field(None, alias="canal_velocity")
    spillway_type: "Optional[str]" = Field(None, alias="spillway_type")
    spillway_length: "Optional[float]" = Field(None, alias="spillway_length")
    spillway_free_board: "Optional[float]" = Field(None, alias="spillway_free_board")
    spillway_discharge_capacity: "Optional[float]" = Field(None, alias="spillway_discharge_capacity")
    penstocks_type: "Optional[str]" = Field(None, alias="penstocks_type")
    penstocks_diameter: "Optional[float]" = Field(None, alias="penstocks_diameter")
    penstocks_velocity: "Optional[float]" = Field(None, alias="penstocks_velocity")
    penstocks_thickness: "Optional[float]" = Field(None, alias="penstocks_thickness")
    penstocks_number: "Optional[float]" = Field(None, alias="penstocks_number")
    installation_method: "Optional[str]" = Field(None, alias="installation_method")
    upstream_control: "Optional[str]" = Field(None, alias="upstream_control")
    inlet_control: "Optional[str]" = Field(None, alias="inlet_control")
    outlet_control: "Optional[str]" = Field(None, alias="outlet_control")
    overhead_crane: "Optional[float]" = Field(None, alias="overhead_crane")
    turbine_type: "Optional[str]" = Field(None, alias="turbine_type")
    turbine_capacity_id: "Optional[UUID]" = Field(None, alias="turbine_capacity_id")
    turbine_numbers: "Optional[int]" = Field(None, alias="turbine_numbers")
    turbine_capacity: "Optional[float]" = Field(None, alias="turbine_capacity")
    turbine_efficiency: "Optional[float]" = Field(None, alias="turbine_efficiency")
    turbine_capacity_flow: "Optional[float]" = Field(None, alias="turbine_capacity_flow")
    alternator_power_output: "Optional[float]" = Field(None, alias="alternator_power_output")
    alternator_number: "Optional[int]" = Field(None, alias="alternator_number")
    alternator_voltage: "Optional[float]" = Field(None, alias="alternator_voltage")
    substation_power_output: "Optional[float]" = Field(None, alias="substation_power_output")
    substation_voltage: "Optional[float]" = Field(None, alias="substation_voltage")


class ProjectDataListResponse(BaseModel):
    success: "bool" = Field(..., alias="success")
    data: "Optional[List[ProjectData]]" = Field(None, alias="data")


class ProjectDataResponse(BaseModel):
    success: "bool" = Field(..., alias="success")
    data: "ProjectData" = Field(..., alias="data")


class ProjectDataUpdate(BaseModel):
    id: "Optional[UUID]" = Field(None, alias="id")
    height: "Optional[str]" = Field(None, alias="height")
    size_class: "Optional[str]" = Field(None, alias="size_class")
    hazard_potential: "Optional[str]" = Field(None, alias="hazard_potential")
    type_of_dam: "Optional[str]" = Field(None, alias="type_of_dam")
    dam_length: "Optional[float]" = Field(None, alias="dam_length")
    crest_width: "Optional[float]" = Field(None, alias="crest_width")
    catchment_area: "Optional[float]" = Field(None, alias="catchment_area")
    design_flow: "Optional[float]" = Field(None, alias="design_flow")
    maximum_flood: "Optional[float]" = Field(None, alias="maximum_flood")
    q100: "Optional[float]" = Field(None, alias="q100")
    q200: "Optional[float]" = Field(None, alias="q200")
    canal_length: "Optional[float]" = Field(None, alias="canal_length")
    canal_width: "Optional[float]" = Field(None, alias="canal_width")
    canal_velocity: "Optional[float]" = Field(None, alias="canal_velocity")
    spillway_type: "Optional[str]" = Field(None, alias="spillway_type")
    spillway_length: "Optional[float]" = Field(None, alias="spillway_length")
    spillway_free_board: "Optional[float]" = Field(None, alias="spillway_free_board")
    spillway_discharge_capacity: "Optional[float]" = Field(None, alias="spillway_discharge_capacity")
    penstocks_type: "Optional[str]" = Field(None, alias="penstocks_type")
    penstocks_diameter: "Optional[float]" = Field(None, alias="penstocks_diameter")
    penstocks_velocity: "Optional[float]" = Field(None, alias="penstocks_velocity")
    penstocks_thickness: "Optional[float]" = Field(None, alias="penstocks_thickness")
    penstocks_number: "Optional[float]" = Field(None, alias="penstocks_number")
    installation_method: "Optional[str]" = Field(None, alias="installation_method")
    upstream_control: "Optional[str]" = Field(None, alias="upstream_control")
    inlet_control: "Optional[str]" = Field(None, alias="inlet_control")
    outlet_control: "Optional[str]" = Field(None, alias="outlet_control")
    overhead_crane: "Optional[float]" = Field(None, alias="overhead_crane")
    turbine_type: "Optional[str]" = Field(None, alias="turbine_type")
    turbine_capacity_id: "Optional[UUID]" = Field(None, alias="turbine_capacity_id")
    turbine_numbers: "Optional[int]" = Field(None, alias="turbine_numbers")
    turbine_capacity: "Optional[float]" = Field(None, alias="turbine_capacity")
    turbine_efficiency: "Optional[float]" = Field(None, alias="turbine_efficiency")
    turbine_capacity_flow: "Optional[float]" = Field(None, alias="turbine_capacity_flow")
    alternator_power_output: "Optional[float]" = Field(None, alias="alternator_power_output")
    alternator_number: "Optional[int]" = Field(None, alias="alternator_number")
    alternator_voltage: "Optional[float]" = Field(None, alias="alternator_voltage")
    substation_power_output: "Optional[float]" = Field(None, alias="substation_power_output")
    substation_voltage: "Optional[float]" = Field(None, alias="substation_voltage")


class ProjectInvestment(BaseModel):
    id: "Optional[UUID]" = Field(None, alias="id")
    total_cost: "Optional[float]" = Field(None, alias="total_cost")
    required_investment: "Optional[str]" = Field(None, alias="required_investment")
    shareholder_structure: "Optional[str]" = Field(None, alias="shareholder_structure")
    equity_investors: "Optional[str]" = Field(None, alias="equity_investors")
    equity_partners: "Optional[str]" = Field(None, alias="equity_partners")
    prospective_equity_amount: "Optional[float]" = Field(None, alias="prospective_equity_amount")
    required_equity_amount: "Optional[float]" = Field(None, alias="required_equity_amount")
    equity_mobilized: "Optional[float]" = Field(None, alias="equity_mobilized")
    equity_needed: "Optional[float]" = Field(None, alias="equity_needed")
    required_debt_amount: "Optional[str]" = Field(None, alias="required_debt_amount")
    current_lenders: "Optional[str]" = Field(None, alias="current_lenders")
    prospective_lenders: "Optional[str]" = Field(None, alias="prospective_lenders")
    loan_type: "Optional[str]" = Field(None, alias="loan_type")


class ProjectInvestmentCreate(BaseModel):
    id: "Optional[UUID]" = Field(None, alias="id")
    total_cost: "Optional[float]" = Field(None, alias="total_cost")
    required_investment: "Optional[str]" = Field(None, alias="required_investment")
    shareholder_structure: "Optional[str]" = Field(None, alias="shareholder_structure")
    equity_investors: "Optional[str]" = Field(None, alias="equity_investors")
    equity_partners: "Optional[str]" = Field(None, alias="equity_partners")
    prospective_equity_amount: "Optional[float]" = Field(None, alias="prospective_equity_amount")
    required_equity_amount: "Optional[float]" = Field(None, alias="required_equity_amount")
    equity_mobilized: "Optional[float]" = Field(None, alias="equity_mobilized")
    equity_needed: "Optional[float]" = Field(None, alias="equity_needed")
    required_debt_amount: "Optional[str]" = Field(None, alias="required_debt_amount")
    current_lenders: "Optional[str]" = Field(None, alias="current_lenders")
    prospective_lenders: "Optional[str]" = Field(None, alias="prospective_lenders")
    loan_type: "Optional[str]" = Field(None, alias="loan_type")


class ProjectInvestmentListResponse(BaseModel):
    success: "bool" = Field(..., alias="success")
    data: "Optional[List[ProjectInvestment]]" = Field(None, alias="data")


class ProjectInvestmentResponse(BaseModel):
    success: "bool" = Field(..., alias="success")
    data: "ProjectInvestment" = Field(..., alias="data")


class ProjectInvestmentUpdate(BaseModel):
    id: "Optional[UUID]" = Field(None, alias="id")
    total_cost: "Optional[float]" = Field(None, alias="total_cost")
    required_investment: "Optional[str]" = Field(None, alias="required_investment")
    shareholder_structure: "Optional[str]" = Field(None, alias="shareholder_structure")
    equity_investors: "Optional[str]" = Field(None, alias="equity_investors")
    equity_partners: "Optional[str]" = Field(None, alias="equity_partners")
    prospective_equity_amount: "Optional[float]" = Field(None, alias="prospective_equity_amount")
    required_equity_amount: "Optional[float]" = Field(None, alias="required_equity_amount")
    equity_mobilized: "Optional[float]" = Field(None, alias="equity_mobilized")
    equity_needed: "Optional[float]" = Field(None, alias="equity_needed")
    required_debt_amount: "Optional[str]" = Field(None, alias="required_debt_amount")
    current_lenders: "Optional[str]" = Field(None, alias="current_lenders")
    prospective_lenders: "Optional[str]" = Field(None, alias="prospective_lenders")
    loan_type: "Optional[str]" = Field(None, alias="loan_type")


class ProjectListResponse(BaseModel):
    success: "bool" = Field(..., alias="success")
    data: "Optional[List[Project]]" = Field(None, alias="data")


class ProjectMarket(BaseModel):
    id: "Optional[UUID]" = Field(None, alias="id")
    overview: "Optional[str]" = Field(None, alias="overview")
    economic_issues: "Optional[str]" = Field(None, alias="economic_issues")
    energy_sector: "Optional[str]" = Field(None, alias="energy_sector")
    electricity_sector: "Optional[str]" = Field(None, alias="electricity_sector")
    sector_policies: "Optional[str]" = Field(None, alias="sector_policies")
    laws: "Optional[str]" = Field(None, alias="laws")
    key_stakeholders: "Optional[str]" = Field(None, alias="key_stakeholders")
    outlook: "Optional[str]" = Field(None, alias="outlook")
    competition: "Optional[str]" = Field(None, alias="competition")
    main_competitors: "Optional[str]" = Field(None, alias="main_competitors")
    competitive_advantage: "Optional[str]" = Field(None, alias="competitive_advantage")
    strengths: "Optional[str]" = Field(None, alias="strengths")
    weaknesses: "Optional[str]" = Field(None, alias="weaknesses")
    opportunities: "Optional[str]" = Field(None, alias="opportunities")
    threats: "Optional[str]" = Field(None, alias="threats")


class ProjectMarketCreate(BaseModel):
    id: "Optional[UUID]" = Field(None, alias="id")
    overview: "Optional[str]" = Field(None, alias="overview")
    economic_issues: "Optional[str]" = Field(None, alias="economic_issues")
    energy_sector: "Optional[str]" = Field(None, alias="energy_sector")
    electricity_sector: "Optional[str]" = Field(None, alias="electricity_sector")
    sector_policies: "Optional[str]" = Field(None, alias="sector_policies")
    laws: "Optional[str]" = Field(None, alias="laws")
    key_stakeholders: "Optional[str]" = Field(None, alias="key_stakeholders")
    outlook: "Optional[str]" = Field(None, alias="outlook")
    competition: "Optional[str]" = Field(None, alias="competition")
    main_competitors: "Optional[str]" = Field(None, alias="main_competitors")
    competitive_advantage: "Optional[str]" = Field(None, alias="competitive_advantage")
    strengths: "Optional[str]" = Field(None, alias="strengths")
    weaknesses: "Optional[str]" = Field(None, alias="weaknesses")
    opportunities: "Optional[str]" = Field(None, alias="opportunities")
    threats: "Optional[str]" = Field(None, alias="threats")


class ProjectMarketListResponse(BaseModel):
    success: "bool" = Field(..., alias="success")
    data: "Optional[List[ProjectMarket]]" = Field(None, alias="data")


class ProjectMarketResponse(BaseModel):
    success: "bool" = Field(..., alias="success")
    data: "ProjectMarket" = Field(..., alias="data")


class ProjectMarketUpdate(BaseModel):
    id: "Optional[UUID]" = Field(None, alias="id")
    overview: "Optional[str]" = Field(None, alias="overview")
    economic_issues: "Optional[str]" = Field(None, alias="economic_issues")
    energy_sector: "Optional[str]" = Field(None, alias="energy_sector")
    electricity_sector: "Optional[str]" = Field(None, alias="electricity_sector")
    sector_policies: "Optional[str]" = Field(None, alias="sector_policies")
    laws: "Optional[str]" = Field(None, alias="laws")
    key_stakeholders: "Optional[str]" = Field(None, alias="key_stakeholders")
    outlook: "Optional[str]" = Field(None, alias="outlook")
    competition: "Optional[str]" = Field(None, alias="competition")
    main_competitors: "Optional[str]" = Field(None, alias="main_competitors")
    competitive_advantage: "Optional[str]" = Field(None, alias="competitive_advantage")
    strengths: "Optional[str]" = Field(None, alias="strengths")
    weaknesses: "Optional[str]" = Field(None, alias="weaknesses")
    opportunities: "Optional[str]" = Field(None, alias="opportunities")
    threats: "Optional[str]" = Field(None, alias="threats")


class ProjectResponse(BaseModel):
    success: "bool" = Field(..., alias="success")
    data: "Optional[Project]" = Field(None, alias="data")


class ProjectTeam(BaseModel):
    id: "Optional[UUID]" = Field(None, alias="id")
    manager: "Optional[str]" = Field(None, alias="manager")
    manager_background: "Optional[str]" = Field(None, alias="manager_background")
    has_board: "Optional[bool]" = Field(None, alias="has_board")
    number_directors: "Optional[int]" = Field(None, alias="number_directors")
    board_directors: "Optional[str]" = Field(None, alias="board_directors")
    management_oficers: "Optional[str]" = Field(None, alias="management_oficers")
    technical_staff: "Optional[str]" = Field(None, alias="technical_staff")
    management_targets: "Optional[str]" = Field(None, alias="management_targets")
    management_agreement: "Optional[str]" = Field(None, alias="management_agreement")
    personnel_practices: "Optional[str]" = Field(None, alias="personnel_practices")
    manager_nin: "Optional[str]" = Field(None, alias="manager_nin")
    nin_validate: "Optional[bool]" = Field(None, alias="nin_validate")


class ProjectTeamCreate(BaseModel):
    id: "Optional[UUID]" = Field(None, alias="id")
    manager: "Optional[str]" = Field(None, alias="manager")
    manager_background: "Optional[str]" = Field(None, alias="manager_background")
    has_board: "Optional[bool]" = Field(None, alias="has_board")
    number_directors: "Optional[int]" = Field(None, alias="number_directors")
    board_directors: "Optional[str]" = Field(None, alias="board_directors")
    management_oficers: "Optional[str]" = Field(None, alias="management_oficers")
    technical_staff: "Optional[str]" = Field(None, alias="technical_staff")
    management_targets: "Optional[str]" = Field(None, alias="management_targets")
    management_agreement: "Optional[str]" = Field(None, alias="management_agreement")
    personnel_practices: "Optional[str]" = Field(None, alias="personnel_practices")
    manager_nin: "Optional[str]" = Field(None, alias="manager_nin")
    nin_validate: "Optional[bool]" = Field(None, alias="nin_validate")


class ProjectTeamListResponse(BaseModel):
    success: "bool" = Field(..., alias="success")
    data: "Optional[List[ProjectTeam]]" = Field(None, alias="data")


class ProjectTeamResponse(BaseModel):
    success: "bool" = Field(..., alias="success")
    data: "ProjectTeam" = Field(..., alias="data")


class ProjectTeamUpdate(BaseModel):
    id: "Optional[UUID]" = Field(None, alias="id")
    manager: "Optional[str]" = Field(None, alias="manager")
    manager_background: "Optional[str]" = Field(None, alias="manager_background")
    has_board: "Optional[bool]" = Field(None, alias="has_board")
    number_directors: "Optional[int]" = Field(None, alias="number_directors")
    board_directors: "Optional[str]" = Field(None, alias="board_directors")
    management_oficers: "Optional[str]" = Field(None, alias="management_oficers")
    technical_staff: "Optional[str]" = Field(None, alias="technical_staff")
    management_targets: "Optional[str]" = Field(None, alias="management_targets")
    management_agreement: "Optional[str]" = Field(None, alias="management_agreement")
    personnel_practices: "Optional[str]" = Field(None, alias="personnel_practices")
    manager_nin: "Optional[str]" = Field(None, alias="manager_nin")
    nin_validate: "Optional[bool]" = Field(None, alias="nin_validate")


class ProjectUpdate(BaseModel):
    id: "Optional[UUID]" = Field(None, alias="id")
    name: "Optional[str]" = Field(None, alias="name")
    description: "Optional[str]" = Field(None, alias="description")
    size: "Optional[float]" = Field(None, alias="size")
    investment: "Optional[float]" = Field(None, alias="investment")
    country_id: "Optional[str]" = Field(None, alias="country_id")
    sector_industry_id: "Optional[str]" = Field(None, alias="sector_industry_id")
    sector_group_id: "Optional[str]" = Field(None, alias="sector_group_id")
    sector_division_id: "Optional[str]" = Field(None, alias="sector_division_id")
    sector_id: "Optional[str]" = Field(None, alias="sector_id")
    technology: "Optional[str]" = Field(None, alias="technology")
    status: "Optional[str]" = Field(None, alias="status")
    commencement_date: "Optional[date]" = Field(None, alias="commencement_date")
    proposed_completion_date: "Optional[date]" = Field(None, alias="proposed_completion_date")
    current_stage: "Optional[str]" = Field(None, alias="current_stage")
    next_stages: "Optional[str]" = Field(None, alias="next_stages")
    estimated_cost: "Optional[float]" = Field(None, alias="estimated_cost")
    contact_information: "Optional[str]" = Field(None, alias="contact_information")
    contact_address: "Optional[str]" = Field(None, alias="contact_address")
    postal_address: "Optional[str]" = Field(None, alias="postal_address")
    telephone: "Optional[str]" = Field(None, alias="telephone")
    email: "Optional[str]" = Field(None, alias="email")
    website: "Optional[str]" = Field(None, alias="website")
    completed_activities: "Optional[str]" = Field(None, alias="completed_activities")
    current_activities: "Optional[str]" = Field(None, alias="current_activities")
    next_activities: "Optional[str]" = Field(None, alias="next_activities")
    outstanding_activities: "Optional[str]" = Field(None, alias="outstanding_activities")
    status_id: "Optional[str]" = Field(None, alias="status_id")
    sponsor_type_id: "Optional[UUID]" = Field(None, alias="sponsor_type_id")
    reference_code: "Optional[str]" = Field(None, alias="reference_code")
    manager: "Optional[str]" = Field(None, alias="manager")
    development_type_id: "Optional[UUID]" = Field(None, alias="development_type_id")
    development_model_id: "Optional[UUID]" = Field(None, alias="development_model_id")
    percentage_public: "Optional[float]" = Field(None, alias="percentage_public")
    percentage_private: "Optional[float]" = Field(None, alias="percentage_private")
    location: "Optional[str]" = Field(None, alias="location")
    nearest_town: "Optional[str]" = Field(None, alias="nearest_town")
    distance: "Optional[float]" = Field(None, alias="distance")
    nearest_capital_country_id: "Optional[str]" = Field(None, alias="nearest_capital_country_id")
    nearest_capital: "Optional[str]" = Field(None, alias="nearest_capital")
    distance_capital: "Optional[float]" = Field(None, alias="distance_capital")
    environmental_impact: "Optional[str]" = Field(None, alias="environmental_impact")
    social_impact: "Optional[str]" = Field(None, alias="social_impact")
    total_investment: "Optional[float]" = Field(None, alias="total_investment")
    equity_investment: "Optional[float]" = Field(None, alias="equity_investment")
    debt_amount: "Optional[float]" = Field(None, alias="debt_amount")
    grant_amount: "Optional[float]" = Field(None, alias="grant_amount")
    outstanding_investment: "Optional[float]" = Field(None, alias="outstanding_investment")
    related_projects: "Optional[str]" = Field(None, alias="related_projects")
    strategy: "Optional[str]" = Field(None, alias="strategy")
    alliances: "Optional[str]" = Field(None, alias="alliances")
